### PR TITLE
#8 make time units dynamic

### PR DESCRIPTION
**Pull request by nck974**
See #8

### CODE REVIEW

**Comment by koaning** [comment]
Did you run `make build` as well? I expected to see a change in the python folder as well but thats probably because the build step has not happened yet.

**Comment by nck974** [comment]
I just executed the `make` and pushed the generated code:
```bash
❯ make      
cd svelte-app; npm run build

> svelte-app@1.0.0 build
> rollup -c


src/main.js → public/build/bundle.js...
(!) Plugin svelte: A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
src/Flare.svelte
68:     <Treemap {root} let:node>
69:       {#if is_visible(node, selected)}
70:         <div
            ^
71:           transition:fade={{duration:400}}
72:           class="node"
src/TableRow.svelte
15: 
16: <tr>
17:     <td on:click={toggle}>
        ^
18:         <span style="padding-left: {depth*10}px; cursor: pointer;">
19:             {#if expanded}
src/TableRow.svelte
35:         {:else}
36:             <tr>
37:                 <td style="padding-left: {depth*10+31}px;" on:click={toggle}>
                    ^
38:                     {child['name']}
39:                 </td>
created public/build/bundle.js in 1.5s
cp -r svelte-app/public/* pytest_duration_insights/static
```
Am I missing anything?

**Comment by koaning** [comment]
That is strange, but that is not what I am seeing locally.

What if you only run `make web`? Did you face any installation issues when you ran `npx install` from the svelte folder?

**Comment by nck974** [comment]
I tried again from another pc with a fresh pull of the fork and using WSL ubuntu:
image

**Comment by koaning** [comment]
Grand, that should do it. I set a reminder to check later tonight locally. It it works I will immediately publish. 

Thanks for the PR!

**Comment by koaning** [comment]
Just made a release, thanks again for the PR!

**Pull request merged**
